baseURL: "https://nirmaljeffrey.dev"
languageCode: en-us
title: Nirmal Jeffrey
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: art
      name: Art
      url: /art
      weight: 35
    - identifier: experience
      name: Journey
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  assets:
    favicon: "favicon-nj.ico"
    favicon16x16: "favicon-nj-16x16.png"
    favicon32x32: "favicon-nj-32x32.png"
    apple_touch_icon: "apple-touch-icon-nj.png"

  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Nirmal Jeffrey"
    subtitle: "I build software by day\nI chase strange ideas.\nSometimes they become useful too."
    imageUrl: "home/profile-picture.jpeg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Projects
        url: "/projects"
      - name: Art
        url: "/art"
      - name: Journey
        url: "/experience"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:jeffattry@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nirmal-jeffrey"
    - name: "github"
      url: "https://github.com/nirmaljeffrey"
    - name: "youtube"
      url: "https://www.youtube.com/@nirmaljeffrey5263"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
